volumes:
  db-data:

services:
  db:
    container_name: hamaralabs-db
    image: postgres:16
    restart: always
    ports:
    - "5433:5432"
    environment:
      POSTGRES_USER: hamaralabs
      POSTGRES_PASSWORD: hamaralabs
      POSTGRES_DB: hamaralabs
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - hamaralabs-network

  app:
    container_name: hamaralabs-app
    image: ghcr.io/vmss2009/hamaralabs:v8
    restart: always
    depends_on:
      - db
    ports:
      - "3002:3000"
    env_file:
      - .env
    networks:
      - hamaralabs-network

networks:
  hamaralabs-network:
    external: true
